services:
  runtime:
    image: harbor.machine:8081/rockwell/ftra-ra:14.3.2.999
    environment:
      - SHARED_NETWORK=false
      - TZ
    volumes:
      - ${VOLUME:-/opt/ftra}:/runtime_persistence
    cap_add:
      - NET_ADMIN
    ports:
      - "127.0.0.1:5161:5161"
      - "5936:5936"
    userns_mode: host
    security_opt:
      - apparmor:${APPARMOR_PROFILE:-unconfined}

secrets:
  web_login_password:
    environment: "WEB_LOGIN_PASSWORD"
